apiVersion: v1
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Demo Application</title>
        <link href="styles.css" rel="stylesheet" type="text/css">
      </head>
      <body>
        This is an example KOTS application.
        <p>This is text from a user config value: 'please change this value' </p>
        </br>
        This is a hidden value: '4BdrzPP4olOVy61A0Pwj9d7xBFpBfoytmdkdjG6L'
      </body>
    </html>
  styles.css: |
    body {
      text-align: center;
      background-color: rgb(224,224,224);
      font-family: Verdana, Arial, Helvetica, sans-serif;
      font-size: 100%;
    }
kind: ConfigMap
metadata:
  annotations:
    kots.io/app-slug: wordpress-enterprise
  labels:
    kots.io/app-slug: wordpress-enterprise
    kots.io/backup: velero
  name: nginx-content
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm94eS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtwQ2VGSkJTRTlCUzNGdVFUZ3daelJvYjBWRVRuZDBaV2xRT2pKS1FuaFNRVWhQUVV0eGJrRTRNR2MwYUc5RlJFNTNkR1ZwVUE9PSJ9LCJyZWdpc3RyeS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtwQ2VGSkJTRTlCUzNGdVFUZ3daelJvYjBWRVRuZDBaV2xRT2pKS1FuaFNRVWhQUVV0eGJrRTRNR2MwYUc5RlJFNTNkR1ZwVUE9PSJ9fX0=
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9999"
    kots.io/app-slug: wordpress-enterprise
  creationTimestamp: null
  labels:
    kots.io/app-slug: wordpress-enterprise
    kots.io/backup: velero
  name: kotsadm-replicated-registry
  namespace: wordpress-enterprise
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm94eS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtwQ2VGSkJTRTlCUzNGdVFUZ3daelJvYjBWRVRuZDBaV2xRT2pKS1FuaFNRVWhQUVV0eGJrRTRNR2MwYUc5RlJFNTNkR1ZwVUE9PSJ9LCJyZWdpc3RyeS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiTWtwQ2VGSkJTRTlCUzNGdVFUZ3daelJvYjBWRVRuZDBaV2xRT2pKS1FuaFNRVWhQUVV0eGJrRTRNR2MwYUc5RlJFNTNkR1ZwVUE9PSJ9fX0=
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9999"
    kots.io/app-slug: wordpress-enterprise
  creationTimestamp: null
  labels:
    kots.io/app-slug: wordpress-enterprise
    kots.io/backup: velero
  name: wordpress-enterprise-registry
  namespace: wordpress-enterprise
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  release: SDRzSUFBQUFBQUFDLzhSN2UzT3F5cmJ2VitGNjk2MTFUdTA4QUdNU2NtcitJU2l2SUVhUTU4bXVYZEFRUUp2SEZGQngzZm5kYjNXamlIbXN1ZVphdCtxa3lvcjBZL1RvTVg3ajFZMi9Eekl2RFFkUGcxMitDWXBOV0piWFlWYUZtMktUbE9IZ2FwQmtiL25nNmZmQlc3SXBxMzhIWVFIekpnd0dUNFBCMVFCNkg1cUNFSWJWK2FFRW02U29randiUEEwbW00YlkxQmtCOHJSQWd3WlhnN0x5cXJvY1BBMDZJbGVETEs5QzFFVGRFRUpZRVZVY0VsNVJ3QVI0aUE1aGFBcmhZMEpaa2tXb3V3d1J5ZFRMZ3ZMcE5TT0ljRi9rbTRwNG1VLytyWTVuMDIvLytJOTE3WWVnZ2tRVVZrU1JCeVZ4ZlkwMlhSWWVDSWxOV01EZmZ5ZlVVOE9QSDhRMUpGNEhYbEhjb0ltYkxLekM4aWJKYjlHY2I1K0o2ZXJqMkNRckt5OERuNDkvSFJEWE9iRXE4Nnp3cXZqYjYrRDNtNlFLMC9LL3lYL2RwR0hsQlY3bDNhRFZmcndPL3JPM0pXNnVMc2VTT3RYKy9UTFhsaDgzOXJOOS9lTWtrdy9MbDBVSWJrQ2VWVjZTaFJ2TUNGb1JmK21hWC9KTjFYRUU0cHg0SFpoSm1WUkVYRlhGMCswdFJUL2NrRGZrRGZYMFNENlNSSlVUZFJrU1RWNXYraHA4SGFENUo4NS93akZpNHZvdDMreThUZEJqSDlGLytzZWxPRjZ6d1krckFZaTlUWVh3ZXBJait2N0hDTitHbTdKRktIbEQzWkFmY0RzbXhCQ21CS1pNdk9VYjRyblQ5T0JxNEJXSjJSSFkwcmlsT0xkUU45UTlwbGsxQmVLaEp3akVMc3pCZXZDVTFSQmVEYW93TGFDSHdmL2ZIYzlkNDYwNlgwNzFtMnBmSVFieHhnWXovUzdTYUpPVVJDMTNkVFlHSWx0Nmxob0hBdHo2Q1dzYTYxM2taT3NJWkdidHA3QjJHNWIwQlBQZzZ1ektwNm5Lc1VacmNNaWZ3MkZaU1FKTUpXNWtPZGFlY3UxWjdWbWpES1RtQVRRajZLZDg0Z3ZtV2hJcGhzdXFCMFZuRzhjYVphNCtYbnNDY3dpNDhmMkxQcTdObEM4RHl6d29hSzJoRE1Gd1Z1TitjUmE5MmVTenhMRVBZVU5HSU9Wcmx6WWlKV1BqUUlnUG1HNHlqanhSSTRGWVBiUzhMRDZsRndoN1BCNE0wVGl6ZGptV2VWdm1Xd1U5YzFydUQxVlNTZU10R0M2aU41dDZDSnR4RFFTZTlOQzRSUjVKSXVZZit1a0M4OVR1L1VoblVXRCtYR3VQWkZTNENaTFRpSFFzV0lObW5DeFRadTJhN0Jaa2k2UXZLMENiVFpEQ2xhdVB5TkJtNFdrL3JoM3YvS0ZNU3RQUml6WTEzNHdwbzVzVGN2MHNWSlNUbXF0QTJFVXUwaDlIVm43S1Y2NnQ3aHhMaFloSGlSdnBycldIanExQ1pUMktmY3M4QUlGZnVUckx2T25qeW0vWTc0Qm0ycjFOeUNSc1JnY2dtQ3NsUS94cEIrdkFCa282MnJxQ3VVQTh2T2xTMVBGcHo2SndXRWFlTlZyNW9ybDI5WEVDVW5QbkMzRGwyQnAwT2VvUUNId1RDR2FqV05VMkVHZTFtNW1sTHlBK2pFVGk3cERzaXMvMnFKdGpSdWJpVFdESjBCbHFwU1FFTU9EWTJxYzFDSnB4cFZnWGU4SDZNVkt6ZEMzKzRPcWp1V05SRUF6WjJLRU50RWFrV0krUmw2bGJIMk1sWXFTc3JEMWJnNzZ0K2pPZXJNRlFpd01SWVlSZnV5TENpQW9CVmU1c2ZSUzdndGE0dG5wNDA2V1dWMHZOL1liTkExSGJ6WlBIclh6bStWN3U2Mmo4RXh3SVRPeE81ZGdYK05xaHpVWktldGpQVkFneXQzQm9vdzVFdU1QNlFyamp4aEdTa1RrMTdxVXBKQ1dCaWtPZEpSMnJncEl3amR6VUhFb0NWZmlaU1NMOXVDblRITzE2NXRQOGVwSHlwV09OVnE0dFJibzVqZ0xoTVhKU0kzSnNOL2FzZmV5a2U2aEV4M1ZPSHg1dUE1MWRPZFpkRk5BODZkQlJGQWd4bEVTVmRHeU5BZzI3ZFJNMkNYVzJDYXdSdG5tSkM5N3A3dGQxQm9idVN1S29vZFRhY3UzUWU4b1ZqRWpLWkFpRWZlSFFQT2xhaXdycERtUWFCQW0xOFlmYVFVbGR5aGYyTmFLSFpJcnNTTjdsa1NTWWQwQmdtb0JqbDVvcFc3cWg4allKRnkvNkl2ZUdadUphS3VsemJPYmFpK1BhdjJwUGFFOXM0YWRxR1ZnYWxEaTVjZTJUTHpYWGlvM2tKWk91TFZVZXpaQ2dHYVdCdFMveEdyb1VLVWxya3dyR0pWc2lHNUk0K1NGczBLZnpsYmxuamRhdUhVVktkcEwvcUh5bjI1N2ZIZStlRVc5MjlhQmtGSVBzMWJWRzJBZExHY1ZJeVJyNVUralE4VllTWWpJUXgvZEs4N2cyU0ZNMzEzQ2ltWXhzVEFxc3E4K3dlWlRuVDMzZWd0NVRZS2hCc0lhTFA0WHpzNjRXUzFKN1c2NTVWVnQrNHZORWR1dUtzMGpScWJxUEg3UlBCY3JRRjh3WTBFYTl2TkFqeFVnY1ZVcWNIQU54WEdQZDIzTHQyc2kzakFxL1lUQ3RGL3RYY1hmaDEwckhabmRLaXZsdC9CVGJZKzFaajF2UEdpRy9XRHUwd1h6S0o4YVM5Rk9mNVZzbTZWaGFIQWpUdXNVcG1UeGZ5bTZ5SkVmR3dvQnp6WlMvamh0SWhuL0JQbVdlZmRGNFpyNHdLRjdpcUswa0ZBZWZIdTBjVzh0ZmRQbEJ5ZFNkYTgxcWgyYnFRT0FMUHpXYm8wL0Z2djc0dmNPSmE4dW5HTlB6cytQRVRPSEJzeGR0WEova1crVXdiZFRtYnFlc3h2VnNtZC9OSnRGT0VyV3RKT0tjWk9RUHpVWVMrTjFKVjU3RjFCTHlhYjE5L3pKZVJCeXZLK1JQQTVwdlhHNjhOcWJNMUNaSDdOSXdvdmxrZkRlYjVPc0Z5Y3pOS1M4djE2WnVVK3lMQVJmdmNvUDgyK0RIMVNlSjJiL2pFQmJocHJ5cENuak96Y0podVgyT0NqNFUyUmpsR3RqdnR2RXo4bW5uK0t6bXlLOG9VZjVkR1hhNTFkcTEzTUpQZndXMzFObU9CVE4xYkxNTXVIRzlvT01ZWklzak52djVHY2JMUzREMG1zSzFxN09Qa3FpaEdMQ1NKczVCRW5kUklNcUZiNnFVbTdwRnlJMFRSWmMreVpkdzdvajJPUUdwR1FlQ0VUa3QvM0ZnN1VsSndQNThKSWs4NVZqN3drMGhkRG1VcDQ2ajFuZmVQWnUwZ2RhaS9GUnQ1OXVMU0YzTklnZnpQb3VRM2gwYjQrUGcweFNVcGhkMmVhVERwcDVsbHNpZk9MWU1KV0ZmK0JaRU1zTnhNaERpQWpUakhPWENXTzVUYlc0MExNSlI0YWNnQWtNV09zMjY1dFl3bGNRT1N5ZmFQWC9Jcmp5VUYzRnNHNk1FU0VwaVVQakNEc2Zpd0ZiYi9UVnMzTzU5MSszek9XRXVkT1JabzErUE0zYUhrY0x0KytKZTNGd09YUWd5dVVCK3I5TlhMMWM5NTNGL1MvOGxvUHYwdFZZZWs1eVJCQTI2S1UvNTRpSlMxa2Q4cjF2Y0s5Q05mZEZFdnZwclhsSHVMeURmcWNYSTMzYTBQOFR2aS8xOTdPTllFdFU5VGpPbVowMjdQOCtpbG9IbHBwNGRSVkpDSnIxNkJ2cGk2eStPenp1UXdqb1FuRWhLeklPaW13Y1UrOTc3MUk2M1ZsNlVuODR3ZHZIYUtheU1vWm02S2J5VE9LbVNrbjZzSGEwdjF2NjBGdm5FdGxwN1B1R3k5U3RJaHpTdTl4RHVLRUNiYTBtUVI4ZmM4WVRYMHJGazZITi9HWWRIT2hjWS9GUkc3MzNPNmRrODgvbUliQXdJZSt5L3BhUk1KRTUrazVLLzc0TlFUZXZUZDVFdjhBbktaN2drMzU3SEkxekMrcy9VT3FmNVVqS3UwSHhQTUV0Zkh4MDhqbW5sTU1sL3VYNDY2dTZVWXp6LzZueEFJK3lwcEQrVVoxaVg0cXhQNjFTL1QxbzlqVmdnc3Bacnl3Y2NReEhXVW40SHVCSE83VUU2Z29HQTYrcXRnbTFRTFh6Njd2NllKMzlCWXhjQjI5d0dGN2JhMWMxZjVXT1ZZNDFpbHpiWGlpV1A1c21IM0dUcDJqTHRXUmUyMTlrRGZtN3laNlBidS9TM2RmdTVIS2svMmdPMjhaYjNYNm9STHVxWUwrVlBRMXpEK3FrS1A1RlA2MmYrUURhTG9ReHh2ZEhhK3pFdU1lbngrZERKVitCWERzMVFmbmFNaWJZSy80WU0yM01FNDBSVG14LzNXcjNENDhjemttN09vblk2M2k5eW56WjM0T0svVVkrdCs3R21rOEhDVWxmKzBLd0Q3cWlici8xL2p3LzUvUDNUK3Nka0hWcmRCdGFJUE9aamYzQ3VkUFQ3MGJjdmNzbHc3NlVGREs5Qm5yMGxVZW9WTjQyWDlySktSU2NyaENUUDdGdXRzK2ZTcXZEVHhiMDBWYmQrNmhZdVNjVmdYRlN1cmNXdXdKUE9Na2ZWNGduSnRVdkRPdVFvbk5tNDFvamtVbHlOM09OVHVMWktyVDFScS94SkhyMk4yMU9GRjQ1Zis3VGFubkFKTWVsYnUzK2k4UkkzZm16SDNqMmZUaDVlaEJnNjF1TFVmMnlqWUNCTTIycUFveUN3elNKWWtja0NWeGxJSzVTQmFSOHJVTVRYaTQ2MEhKTUtqZGQ3T0diTUI5ZGVNSUd0cGNveVNwVERlVjNFU3lCQTBoZU1mMnFDV2ZrTnkxNmNpcTUyMjFQL0pXLzd3ay9MeUJObDZLN0lCQXkxa1k4dFZEMkFSb3BBYXBZdnVud0lSRmk2dHBxN2xrbEtDWXRsY2VZUmp6M1RuZXkybm1ERzdvVmM1SzBycmkvV05uRjJ5cUpQN0Njc0RBVytBc0llWmJvdkpvOHlXdlpralVqZjlRWGY0dmlmdmZtWUQwbHdHNThtVVNhT3NvRUdaMU1JRXcxTFkydGM1cEdNVDB2UDFva3FQVGVGbVpLYWQ0NUY3WHpCbko1UTN5SWVvenBEZXdLVFMza3J0Tnk4OUUrZWVDMzM3Rm1FUG83TzVwNmxyVjNyTGdwYU92Y1NGMXllU3FRbi9rYkhzVWUrY0RVTnpyTGptTVNudGRGcHJSZU95UU9CS3ZHenFKS2h0VWZXdmdMRDJiMGs3dHA1cmJ5amNIZmlyNVdSWXZHbFp3WDFQR0ZYQ0dldUxUMTBjaFhrMktHckRLUU01YWVMeXFHWjBoOUs5NUlvWjA0U05iUFZvcHl0SkZLWlNJM0tyWHZ6M0syUEswMis4cXc5aW5Zb2VxNVJCRlE0bGdVcGpIMXVGK21DV1FhcFNTSk1LaHg3Y0t6UlFiRlZDRktZenM5OHBzZ0dGRnN0d3RTNGx5YlQzWXd6am11eGY4S0R0RGRxYVpoVmY4YUZvS0pibkcyRDFmVFpvMkh0VHZKSUUxQVFZRWErWmRiQnoxd0pjaEVvb1V2TkVoenlvK2o1SFpqa2taOEdoWjlGejdqSXduM3NBU2ZyUTIwTFZxZXhWQndJYXI0OEJ2ZDVCeWRjTE41THdpanpyTkVkMm40Z21NZzhVRUo4ZnhUSE85NWFkZmdmYUgzazZkVHVXS1BhSDJxdGk4aG05MzBUYzFKKzVRM05uWks1cURCcy9EWXBTQnhMM1FUMnVBcFNwZ3dzQ29KRFI3ZHlUaTd0NkRyUGV6L1M3QitzOU5vVi9STzVkcnpEeXJHQ3ovdEVkK3VMWnVVYUZBNUVmWm9TTjY2T0J3K2RIQlVMRjFqUXp4YlBGd2ZHUWp2ZndKY0tlYVFNelFOSW1BTktDRjJkT1lhTjF1eVVYWDk5R1FLYW9VQ3F3bmRyUjZkaS9FTTcwcEZsVnY0UUpZYmpiTFl5NktXMXp2cXliK2VydXdDNXJJT3htd25rdTM2MmNXMmVjbTMxNS9RUHN1cjEzRW1uaXlGTDRmN2xlT2YzK250Ni9Wby8vUkRheDh6Um5TNHRmamQvZHlpUGs1VGxwMWo1aVVtWDRXYWJnUENkUFg5NmVXZXJTbURMWlp2WTVwV2lrOCtPelJaZEViYktvNzZ0RzZma2JQSC8xYzV4ZUp3bjdOeW5OV2dJVElQdFFXd3ZxRTV5UVlXa1A1VEplVEsrbTNXWWJpK004SnhKSHMwbjBkMGN6MVdSRGE0Q2dXbE84MUY0UFBQWFA4eHVrOUgvd1gxUGZORThvTVJaTjhlb3ZUMDg3ZkJFUnFEYjMvZ0x2M2k1eGptcGJQYzIrUEd2cThIV2czVllEcDUrSDdSWkkvcDJoTXdrZlBOcVdKbG9CSUpLMjBvRWJUT0JadzZ1Qm5FU0JHRjJHdFUrSFR0L1hBMlNMTnFFSlY0Z3pEd2Zoc0hnNmMyRFpZajZ5dWQ2QTQvUFY0TWpRdEhRNDMwM0IrdXlDamZTeStESGo2dEJDZUl3OVU0WDNtOEp2THpzdm9tU0txNzkyMTIrV2IvQmZGZmVwbDZTM1RSOXVKL01aMEd1bjdtVXFURU1SSlRwUktkd2dNK3grMktXbS95N3ZEdkJiWnhKZXY1ZFNhbjFSWnVsYlozbThmdHpBbnJ6cHQrZms5SE9UMEhHUmNWM241WmIyQXBxNDFvODZlcFVjenAzT3NFUlpHWU5HcXFGbWlXajJvaFNMQlN1ek1NNUhHZ1FpRjJZcWZENXR6MURZWGgxREVGYmg0NmhRMWZid05iR0NMSW5uazc3UDk3N3gyNTdqZ2tWRHQvZDREdGd6M0lMMXpxN2RzVFRQTUg5R2FydEpJN2FTNXkwRFFRK0E4MWpJazEyankvY09KSEZTdFJOVFRJTitjMVltOEtiTGozZ090SzZPNTNwMzg4ekZRWWNoZmphQmZieExHcEprWTRGN3VlSjlxQ1IwTkI1azdNcG1kZFcrWDRta2crUzRCYm5MQW11NXdtYnViYjJodGJ2WkhBS1VWTjhYNXlBbEs4ZE9tcnBMenEzMEFRV1NsZk1sU2M4UmxJeVcxbkRUL2s1elgrdzlVVis1SDBka29Gc1RtTnpBUmxkTTV3VlNNMFVORXp1V3Z3YU5BenpyRXVkekR4cmNZL3ZQM25tUk91RERuUjhMc1F1VUNxQVFyUEVQVWF1WU83QTdoMi9uSnk3MWg3WDJBQ1pyMkRXem5BZEJUYTdidThLblZRU1l1Z0x5Q1h3SzQvbU0xY2YxeEpIclZGcTVLY3d4U0d1a1Q3dzBOWC93aFJYS2UyNUFidjFFM2JpQ1h6dHAyWXBDZndCME16S3MvajJUSnlHcE1leHBDY1lrWlBKc1orcWVhZWZEb3ZhMXFFckNGYjVWaGxlM0VOc2d4VHRnV2tVU3kyOVpZSHZPOEh3akRkTWY5SVB4MndNMHVBd1Q5ak9YczQyTks0VWk2Y0M0VEZTN0hVM3g3Vkc5RVhvNUdYZW1PN2xCY2tibXFHOUxVeFd0aW50UlNmTitUd1pyOE5oR1FIYVJEb2xRVFBTTlpPZDZZYkttbE56YXBQOFFqY1pZMGxXL0RMcDNjZC9UbmN4VDlpaFA1VFhBTDlQTUt2YUNrSGVnUlFlM1A3Y2FZY256bGp6OHdVWkgrODc4MGdXcXdkVWxiZzJlMURTQ3h6Vi90QWtnWWo1N0hEZXZoL1R5YXV6UTNQS2k4ZTdxbnVKMHg3Q2hrVWhaUWVhVVdkRFNzcFFnY2hTZ1RoRGFXVjJldi9rd3E2NCtJRDZQR3VVUGV0cy83Nm1weE9tbHFacWp0SmgxOXBGanEwZWZGb3Qybk1nZHVqWlduNDhWM3BuRTJOOG5vUlNZRmRnVmg1dE52UGtjWHQ1anNUUXJqVmErME9wY3VoOU1VOHZmYUowcFA4dVhXOWNYTTJkNzJTNk15T09yQnpiSlAxbVhJVm4vd0Q5ekxsSTM0MjF1VmhPNFdSaGFyekdNNnd4aFcvbWxGRTA0NjZUcDJ1cGpXdHJCd1YralRHYlVvMkZFY2pMTlhpdnF3OVlNeVo1Rk5CTTQ0b3NmdjlFUVNXVVlEWkFsQXRBRzUvcWVRRmxkcmxXcFQvUzljbFcrL28rdGZWMGpqOW5QNnl4R3RYZTlYWjIwc2FmMnFWTjBoNmlHREk2K2svdG9HUTRwdnpNUm1TYlpIUWR5V09WSDkvYm10MHJEUk1EWVkzUE0xSGE1RGFqeTNNN1ZPbnJIUTcrUUlhQnZqQlp5VEQyYjB0S2xqVVN6dWRKKzk0T09PUmJoUVkvV3lNRHFNUVYrWktMTHRQcW16aUVhUkpsK1NZOEp4VlN3eTRjVzBOR1hvT0dKZjJHTFZ4NnRBV3BFUVYwRFAyRVRRSUxscTZBWDZMYm5SdythTzZlcFlZMVBBRWVKRkdsd0RHM2xVUVZPZnhTRW9MU3A2WEl0M2pTb2VQQ1QwSFpncGtuUGR1RmtvaGZFTGpzRi9qYUhlY3JTUmhCOTNRSnpzVTdGS3c4T3o0YklqY3RsSVI5OGRQOUNCbXVxK1BFQis5QkVsa0lFaVNVRVZTaXZOWjQ5YzFBZVdWcUlINjdpeEp6clM0bFFTdEFObnRXMHFBSXVNZjJ2d0F6UDJVYWQ1SFhUbFkweXE3OTcxbEI3UTlseUNXajNHM1EyRGpydFIyQzlHN0xKYk5vUVRPVmovaHVqMUlvd0xHcForMGgyT1hmbFV3ZGdqRkt3T1RZdzg5YTFUNHpqV2VCNStjTXk5UnliTG53aCtaQm1zS3BacytlbFl4dGZMcUF6bkR4cktSdzdWclRMWmZrZFNCUU81QXkzN2xrUkFOYTNicUNzZVhTZnRCOGZFWk9TZGxkQWtHYmppZXo2VTBhbkdGZzlteFdtbDdhN011U1pENzdjRkhCZHlkMllzZGlCT2g0RzlCcUREQkcyZHdmQXBUdUQxMWJhbjFsTm9zY21xOGxZUStEMUd4dy90RDZWcjJQWjJtcXpuU2ROWHlhS1kvUVBONnBHRkY3OXMyNkM0T2F0WGQvZUsxWUVwQXEwVDdZTGFBaGlVcGdKY3BSdWZEanFsY2wvS3hlS0dEb2xTRUJZaStMUXFLS2svS0xrdUdPRFRhSGw1ZTdITTdONXA0YWt5KzdGUk04N0ZtK1lOL3lwa3FEZGJBUzdwWEIrNUxoeDlVZzliTGtMU3lyd2RQZyt2cjZOZnZmaEo3WEd4QStFWis5cjN2N3M3UHkxK3o4UnU0VHNhVmVzM1dTQlU4RWgwZk52T0kxTzcwYWpOOFdSMmg0SXJJb3lmYUlVaFZtMVd2VzlTWlpFTzV2NGlxRlQ4VC9SUTBFOFZxVDVCRDhyeUFIcU1RaFVCOXVDdnZkNzF1Nzl0QUxMdHRQUFlncC9DTDFkZmk5VHJiZlhnZGN5ODMxc2luQzF3RnhaTzdiNjZBSzk5VXRXdUcvOEV2SlpWaDlxNnUzNjhmWHdlM250S3VrZ21IYk5RblRuQmozM3NiR0EyNTdJOTVQaGttMkp1Sk4rUGJ0ZFZCV0RRekxHMUNXcndOaUU4S3VLUTdENm5WQUlJbWNHTVNEUHBQQjdVY2h0QjErSGpUdmVWZ2kwQ1VsNFdYRXFYcDluaS8xL2d2bE4rODVMbG9pcDZtSUcrSnRrNmVFUjlSbHVDRmF3TFJRZmlKKyt3cmx2NTM0TFQ0WHpLMi8rWkpib2w5RVB4Ry8vVmtEK2UyZHFONkw1Q1RCQzNpZHRkS0JGTTBqZmo4UlF4SzQ5bUFTWlU4RXdMYjBYNmN1M3dQcmFKUFhXWEFOY3Bodm5vaE41UDhIVGQ5ZEhULy8yUTE5eTdQcStzMUxFOWc4RVdhNENiek11eUxHbThTRFY0UVl3bTFZSmNDN0lrb3ZLNi9MY0pPOFhVNHRrMFA0UkZBaytYK083VDllczc5bThmMkRzSy9zWFcvSGZHM3Q2QkY2ZmdqYlg0MFFDRkpkVjFtRUFEY2pSRDhSM1NrR2FzSS9qRGpPdWNaUFQ4UWppUlVSd2hCVStlWVRnbjl0bys4TzhTLzM2aFZGZVh2ZThLUWIrM2YzL0c0YnFWZUJXT25QdXB5SDhOVXlmcHJRWHgzOXdjdko3NmZqbGl6TEsyek8vWEVJblhWeHN3MWh1TWx2a3Z5MmJiamU1ckJPdy9LRDMwWnp1bTJndi9OUFdycW02L2NDYWYrUzFJcyt0cllMemZJNnEvcDhYWDhlTm9qdUwwVXpYcndxZmlKdTYzSnpXOGJlSnJ6Rnc3SHgzcDRIYjhJU2c2SlBueUJna2liVlpSTVNiSnB2bWlmaU4zcDBQMHQrdSt3RVJmMUUvRFlpeWZTaVl4TityOFB5YTFKRCtndEtWSi9TU2VDZkN2R2pBTUFwMkY2cyt1bVUvZzl3cUt0QjkydWdyMzZ2OCtQL0JRQUEvLzlxVTFKR3NUWUFBQT09
kind: Secret
metadata:
  annotations:
    kots.io/app-slug: wordpress-enterprise
  creationTimestamp: null
  labels:
    createdAt: "1"
    kots.io/app-slug: wordpress-enterprise
    kots.io/backup: velero
    name: wordpress-enterprise
    owner: helm
    status: deployed
    version: "1"
  name: sh.helm.release.v1.wordpress-enterprise.v1
type: helm.sh/release.v1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kots.io/app-slug: wordpress-enterprise
  labels:
    app: nginx
    kots.io/app-slug: wordpress-enterprise
    kots.io/backup: velero
  name: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: wordpress-enterprise
  labels:
    app: nginx
    kots.io/app-slug: wordpress-enterprise
    kots.io/backup: velero
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: nginx-content
        kots.io/app-slug: wordpress-enterprise
      labels:
        app: nginx
        kots.io/app-slug: wordpress-enterprise
        kots.io/backup: velero
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-content
      imagePullSecrets:
      - name: wordpress-enterprise-registry
      volumes:
      - configMap:
          name: nginx-content
        name: nginx-content
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kots.io/app-slug: wordpress-enterprise
  labels:
    app: nginx-2
    kots.io/app-slug: wordpress-enterprise
    kots.io/backup: velero
  name: nginx-2
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: nginx-content
        kots.io/app-slug: wordpress-enterprise
      labels:
        app: nginx
        kots.io/app-slug: wordpress-enterprise
        kots.io/backup: velero
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 32Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-content
      imagePullSecrets:
      - name: wordpress-enterprise-registry
      volumes:
      - configMap:
          name: nginx-content
        name: nginx-content
